# Generated by Django 4.0.5 on 2022-06-30 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(choices=[('ES', 'ESTAGIARIO'), ('AS', 'ASSISTENTE'), ('JR', 'JUNIOR'), ('PL', 'PLENO'), ('SN', 'SENIOR'), ('GR', 'GERENTE')], max_length=2),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='data_nascimento',
            field=models.DateField(null=True),
        ),
    ]
