# Generated by Django 4.0.5 on 2022-06-30 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rh', '0004_alter_funcionario_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(choices=[('ES', 'ESTAGIARIO'), ('AS', 'ASSISTENTE'), ('JR', 'JUNIOR'), ('PL', 'PLENO'), ('SN', 'SENIOR'), ('GR', 'GERENTE'), ('SP', 'SUPER')], max_length=2),
        ),
    ]
